### ISSUE TITLE
Google Colab - implementation

### ISSUE THREAD

**Issue by pilitro** [yhz0118/Video-Stabilization#1]
hi!, I'm trying to implement the code in google colab but I have some issues. I don't know how to solve them, can you help me?
Here is the link to my colab
https://colab.research.google.com/drive/13bMFs8SlXMZQdHgWpQ9iXtYvGJjVMXbr#scrollTo=xJ5X-78BV-0x

**Comment by yhz0118** [comment]
Hi, I think you should look up this website: https://bobbyhadz.com/blog/python-float-object-cannot-be-interpreted-as-an-integer

Hope this helps

**Comment by pilitro** [comment]
thanks mate!, appreciate
